app/ctrl_p/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.conf import settings # new
from django.conf.urls.static import static # new

from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as ctrl_p

app_name = 'ctrl_p'

urlpatterns = [

    # Upload File
    path('user/<pk>/upload-file/', ctrl_p.UploadFile.as_view(template_name='ctrl_p/file/upload_file.html'), name='upload-file'),

    # Files Printer
    path('user/<pk>/printer', ctrl_p.PrinterView.as_view(template_name='ctrl_p/user/printer.html'), name='printer'),

    # Files Waiting
    path('user/<pk>/waiting', ctrl_p.WaitingView.as_view(template_name='ctrl_p/user/waiting.html'), name='waiting'),

    # Files Complete
    path('user/<pk>/complete', ctrl_p.CompleteView.as_view(template_name='ctrl_p/user/complete.html'), name='complete'),

    # Files Printer Admin
    path('admin/<pk>/printer', ctrl_p.AdminPrinterView.as_view(template_name='ctrl_p/admin/printer.html'), name='admin-printer'),

    # Files Waiting Admin
    path('admin/<pk>/waiting', ctrl_p.AdminWaitingView.as_view(template_name='ctrl_p/admin/waiting.html'), name='admin-waiting'),

    # Files Report Admin
    path('admin/<pk>/report', ctrl_p.AdminReportView.as_view(template_name='ctrl_p/admin/report.html'), name='admin-report'),

    # Success
    path('success/', ctrl_p.SuccessView.as_view(template_name='ctrl_p/file/success.html'), name='success'),

    # Success Update
    path('success-update/', ctrl_p.SuccessUpdateView.as_view(template_name='ctrl_p/admin/success.html'), name='success-update'),

    # Search Results
    path('search-user/', ctrl_p.ResultsView.as_view(template_name='ctrl_p/admin/results.html'), name='results'),

    # User Details
    path('user/<pk>/details', ctrl_p.UserDetailView.as_view(template_name='ctrl_p/user/details.html'), name='user-details'),

    # File Update
    path('file/<pk>/update/', ctrl_p.UpdateFileView.as_view(template_name='ctrl_p/file/file-update.html'), name='file-update'),

    # View File
    path('documentos/<pk>', ctrl_p.ViewPDF.as_view(), name='view-file')



]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Core: auth
    path('', include('app.core.urls'), name='core'),

    # Ctrl_p
    path('', include('app.ctrl_p.urls'), name='ctrl_p')
]

app/ctrl_p/models.py
from django.db import models
from app.core.models import CreateUpdateModel, UUIDUser

# Model referente aos arquivos enviados para impressão
class File(CreateUpdateModel):
  '''
  STATUS = (
    (1,'Aguardando Impressão'),
    (2,''),
    (3,'')
  )
  choices=STATUS
  '''
  user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='users', verbose_name='Usuário')
  name = models.CharField(max_length=20, verbose_name='Nome')
  copy = models.IntegerField(verbose_name='Número de Cópias')
  file = models.FileField(upload_to='documents/', verbose_name='Arquivo')
  status = models.IntegerField(verbose_name='Status de Impressão', default=1)
  uploaded = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name = 'Arquivo'
    verbose_name_plural = 'Arquivos'

app/ctrl_p/forms.py
#coding:utf-8
from __future__ import unicode_literals

from django import forms

from .models import File

class FormFile(forms.ModelForm):

    def save(self, commit = True):
        file = super(FormFile, self).save(commit=False)
        if commit:
            file.save()
        return file

    class Meta:
        model = File
        fields = ['user', 'name', 'copy', 'file']
        labels = {
            'user': 'Usuário',
            'name': 'Nome do Arquivo',
            'copy': 'Número de Cópias',
        }
        widgets = {
            'file': forms.FileInput()
        }

app/ctrl_p/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse

from . import models

from .models import File
from .forms import FormFile
from app.core.models import UUIDUser

from django.contrib.auth.decorators import login_required #new
from django.utils.decorators import method_decorator #new

# View do usuário comun com os arquivos aguardando impressão
#-----------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class PrinterView(DetailView):
	model = UUIDUser
	template_name = 'ctrl_p/user/printer.html'

	def get_context_data(self, **kwargs):
		kwargs['files_print'] = models.File.objects.filter(user = self.object.id, status = 1).order_by('-uploaded')
		return super(PrinterView, self).get_context_data(**kwargs)

# View do usuário comun com os arquivos aguardando retirada
#-----------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class WaitingView(DetailView):
	model = UUIDUser
	template_name = 'ctrl_p/user/waiting.html'

	def get_context_data(self, **kwargs):
		kwargs['files_waiting'] = models.File.objects.filter(user = self.object.id, status = 2).order_by('-uploaded')
		return super(WaitingView, self).get_context_data(**kwargs)

# View do usuário comun com os arquivos concluídos
#------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class CompleteView(DetailView):
	model = UUIDUser
	template_name = 'ctrl_p/user/complete.html'

	def get_context_data(self, **kwargs):
		kwargs['files_complete'] = models.File.objects.filter(user = self.object.id, status = 3).order_by('-uploaded')
		return super(CompleteView, self).get_context_data(**kwargs)

# View do usuário administrador com os arquivos aguardando impressão
#--------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class AdminPrinterView(ListView):
	'''
	Classe responsável por renderizar os arquivos que estão aguardando para serem impressos. Visualização do Usuário Administrador
	'''
	model = File # Criando Model da classe com base no model File
	template_name = 'ctrl_p/admin/printer.html' # Informando a classe o template que será utilizado para renderizar os dados

	def get_context_data(self, **kwargs):
		kwargs['files_print'] = models.File.objects.filter(status = 1).order_by('-uploaded') # Pegando do banco de dados os arquivos que estão aguardando para serem impressos
		return super(AdminPrinterView, self).get_context_data(**kwargs) # Retornando os dados para o template, para serem mostrados ao usuário

# View do usuário administrador com os arquivos aguardando retirada
#--------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class AdminWaitingView(ListView):
	'''
	Classe responsável por renderizar os arquivos que estão aguardando para serem retirados pelo solicitador. Visualização do Usuário Administrador
	'''
	model = File # Criando Model da classe com base no model File
	template_name = 'ctrl_p/admin/waiting.html' # Informando a classe o template que será utilizado para renderizar os dados

	def get_context_data(self, **kwargs):
		kwargs['files_waiting'] = models.File.objects.filter(status = 2).order_by('-uploaded') # Pegando do banco de dados os arquivos que estão aguardando para serem impressos
		return super(AdminWaitingView, self).get_context_data(**kwargs) # Retornando os dados para o template, para serem mostrados ao usuário

# View do usuário administrador onde ele poderá gerar relatórios de uso
#-----------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class AdminReportView(TemplateView):
	template_name = 'ctrl_p/admin/report.html'

# View para consulta de dados do usuário, será mostrada quando o administrador realizar
# alguma pesquisa e selecionar um usuário dos resultados apresentados.
#------------------------------- 
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class UserDetailView(DetailView):
	'''
	Classe responsável por mostrar ao usuário administrador os dados de um usuário
	'''
	model = UUIDUser # Criando Model da classe com base no model UUIDUser do app core
	template_name = 'ctrl_p/user/details.html' # Informando a classe o template que será utilizado para renderizar os dados

	def get_context_data(self, **kwargs):
		kwargs['files_print'] = models.File.objects.filter(user = self.object.id, status = 1).order_by('-uploaded') # Pegando do banco de dados os arquivos que estão aguardando para serem impressos e que estão relacionados ao usuário atual
		kwargs['files_waiting'] = models.File.objects.filter(user = self.object.id, status = 2).order_by('-uploaded') # Pegando do banco de dados os arquivos que estão aguardando para serem retirados e que estão relacionados ao usuário atual
		kwargs['files_complete'] = models.File.objects.filter(user = self.object.id, status = 3).order_by('-uploaded') # Pegando do banco de dados os arquivos que estão concluídos e que estão relacionados ao usuário atual
		return super(UserDetailView, self).get_context_data(**kwargs) # Retornando os dados para o template, para serem mostrados ao usuário

# View responsável pelo carregamento do arquivo para impressão
#----------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class UploadFile(CreateView):
	'''
	Classe responsável por realizar o upload e salvamento do arquivo no banco de dados
	'''
	model = File # Criando Model da classe com base no model File
	template_name = 'ctrl_p/file/upload_file.html' # Informando a classe o template que será utilizado para renderizar os dados
	success_url = reverse_lazy('ctrl_p:success') # Tela que o usuário será enviado se sua requisição for concluída com êxito
	fields = ['user', 'name', 'copy', 'file'] # Formulário que será utilizado no template para realizar o upload do arquivo

# View da mensagem sucesso, será mostrada quando o usuário comun realizar o upload de um arquivo para impressão
#-------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class SuccessView(TemplateView):
	'''
	Classe com o template success, que será renderizado quando o upload do arquivo for concluído com êxito
	'''
	template_name = 'ctrl_p/file/success.html' # Definindo o template de renderização da classe

# View da mensagem sucesso, será mostrada quando o usuário administrador realizar uma atualização no status do arquivo
#-------------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class SuccessUpdateView(TemplateView):
	'''
	Classe com o template success, que será renderizado quando o arquivo for atualizado com êxito
	'''
	template_name = 'ctrl_p/admin/success.html' # Definindo o template de renderização da classe

# View que renderizará os resultados da pesquisa realizada pelo usuário administrador
#---------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class ResultsView(ListView):
	'''
	Classe responsável por listar os resultados da pesquisa realizada pelo usuário administrador
	'''
	model = UUIDUser # Criando Model da classe com base no model UUIDUser do app core
	template_name = 'ctrl_p/admin/results.html' # Informando a classe o template que será utilizado para renderizar os dados

	def get_queryset(self, **kwargs):
		if 'q' in self.request.GET: # Verificando que a variável 'q' foi passada durante a solicitação
			object_list = self.model.objects.filter(first_name__icontains = self.request.GET['q']) # Pegando do banco de dados os usuários que foram encontrados a partir do valor passado na requisição
		else: # Caso não tenha sido passada durante a solicitação
			object_list = self.model.objects.all() # Pegamos no banco de dados todos os usuários cadastrados
		return object_list # Retornando os dados para o template, para serem mostrados ao usuário

# View que renderizará um arquivo já existente no banco e dará a opção de atualizar o status do arquivo
#--------------------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class UpdateFileView(UpdateView):
	'''
	Classe responsável por realizar atualização no model file
	'''
	model = File # Criando Model da classe com base no model File
	template_name = 'ctrl_p/file/file-update.html' # Informando a classe o template que será utilizado para renderizar os dados
	success_url = reverse_lazy('ctrl_p:success-update') # Tela que o usuário será enviado se sua requisição for concluída com êxito
	fields = ['user', 'name', 'copy', 'file', 'status'] # Formulário que será utilizado no template para realizar o upload do arquivo

# View que renderiza o arquivo PDF na tela do navegador, para os usuários poderem visualizar o arquivo no próprio navegador
#-------------------
@method_decorator(login_required(login_url='/'), name='dispatch') #new
class ViewPDF(View):
	def get(self, request, pk):
		kwargs = models.File.objects.filter(id = pk)
		with open('uploads/%s' % kwargs[0].file, 'rb') as pdf:
			response = HttpResponse(pdf.read(), content_type='application/pdf')
			response['Content-Disposition'] = 'inline; filename="some_file.pdf"'
			pdf.close
			return response

templates/ctrl_p/admin/index.html
{% extends '../../core/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Solicitação de Impressão
            <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Requisição de Impressão</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
            <!-- Default box -->
            <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Painel Administrativo</h3>
            </div>
            <div class="box-body">
            <!-- Inicio da Aplicação -->
            <div class="search-user">
                <form class="navbar-form navbar-left" role="search" method="get" action="/results">
                    <div class="form-group">
                    <input type="text" class="form-control" placeholder="Pesquisar Usuário" name="q">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" href="#printer" role="tab" data-toggle="tab">Arquivos para impressão</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#waiting" role="tab" data-toggle="tab">Arquivos aguardando retirada</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#report" role="tab" data-toggle="tab">Gerar Relatórios</a>
                </li>
            </ul>
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane active" id="printer">
                    {% if files_print|length > 0 %}
                    <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome do Documento</th>
                        <th scope="col">Data da Solicitação</th>
                        <th scope="col">Solicitador</th>
                        <th scope="col">Status</th>
                        <th scope="col">Opções</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for file in files_print %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ file.name }}</td>
                            <td>{{ file.uploaded|date:"d/m/Y" }} às {{ file.uploaded|time }}</td>
                            <td><a href="{% url 'ctrl_p:user-details' file.user.pk %}">{{ file.user }} {{ file.user.last_name }}</a></td>
                            <td><span class="label label-danger">Aguardando Impressão</span></td>
                            <td><i class="fa fa-print" aria-hidden="true" style="margin-right: 10px;" title="Imprimir"></i><a href="{% url 'ctrl_p:file-update' file.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Editar"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  {% else %}
                  <div class="not-found">
                    <h3>Nenhum arquivo aguardando impressão</h3>
                  </div>
                  {% endif %}
                </div>

                <div role="tabpanel" class="tab-pane" id="waiting">
                    {% if files_waiting|length > 0 %}
                    <table class="table">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nome do Documento</th>
                        <th scope="col">Data da Solicitação</th>
                        <th scope="col">Solicitador</th>
                        <th scope="col">Status</th>
                        <th scope="col">Opções</th>
                      </tr>
                    </thead>
                    <tbody>
                        {% for file in files_waiting %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ file.name }}</td>
                            <td>{{ file.uploaded|date:"d/m/Y" }} às {{ file.uploaded|time }}</td>
                            <td><a href="{% url 'ctrl_p:user-details' file.user.pk %}">{{ file.user }} {{ file.user.last_name }}</a></td>
                            <td><span class="label label-warning">Aguardando Retirada</span></td>
                            <td><a href="{% url 'ctrl_p:file-update' file.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Editar"></i></a></i></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                  </table>
                  {% else %}
                  <div class="not-found">
                    <h3>Nenhum arquivo aguardando retirada</h3>
                  </div>
                  {% endif %}
                </div>

                <div role="tabpanel" class="tab-pane" id="report">
                    <div class="not-found">
                        <h3>Página em construção</h3>
                    </div>
                </div>
            </div>

            </div>
            <!-- /.box-body -->
            <!-- /.box-footer-->
            </div>
            <!-- /.box -->
        
        </section>
        <!-- /.content -->
{% endblock %}

templates/ctrl_p/admin/printer.html
{% extends '../../core/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Solicitação de Impressão
            <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
        </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-print"></i> Requisição de Impressão</li>
      <li class="active">Aguardando Impressão</li>
    </ol>
    </section>
    <!-- Main content -->
    <section class="content">
            <!-- Default box -->
            <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Painel Administrativo - Arquivos Aguardando Impressão</h3>
            </div>
            <div class="box-body">
            <!-- Inicio da Aplicação -->
            <div class="search-user">
                <form class="navbar-form navbar-left" role="search" method="get" action="/results">
                    <div class="form-group">
                    <input type="text" class="form-control" placeholder="Pesquisar Usuário" name="q">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="col-md-12">
                {% if files_print|length > 0 %}
                <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome do Documento</th>
                    <th scope="col">Data da Solicitação</th>
                    <th scope="col">Solicitador</th>
                    <th scope="col">Status</th>
                    <th scope="col">Opções</th>
                  </tr>
                </thead>
                <tbody>
                    {% for file in files_print %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'ctrl_p:view-file' file.pk %}">{{ file.name }}</a></td>
                        <td>{{ file.uploaded|date:"d/m/Y" }} às {{ file.uploaded|time }}</td>
                        <td><a href="{% url 'ctrl_p:user-details' file.user.pk %}">{{ file.user }} {{ file.user.last_name }}</a></td>
                        <td><span class="label label-danger">Aguardando Impressão</span></td>
                        <td><i class="fa fa-print" aria-hidden="true" style="margin-right: 10px;" title="Imprimir"></i><a href="{% url 'ctrl_p:file-update' file.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Editar"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
              {% else %}
              <div class="not-found">
                <h3>Nenhum arquivo aguardando impressão</h3>
              </div>
              {% endif %}
            </div>
            </div>

            </div>
            </div>
            <!-- /.box -->
        
        </section>
        <!-- /.content -->
{% endblock %}

templates/ctrl_p/admin/report.html
{% extends '../../core/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Solicitação de Impressão
            <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="/dashboard"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Requisição de Impressão</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Painel Administrativo - Gerar Relatórios</h3>
            </div>
            <div class="box-body">
            <!-- Inicio da Aplicação -->
                <div class="col-md-12">
                  <div class="not-found">
                    <h3>Página em construção</h3>
                  </div>
                </div>
            </div>
        </div>        
    </section>
        <!-- /.content -->
{% endblock %}

templates/ctrl_p/admin/results.html
{% extends '../../core/base.html' %}
{% load staticfiles %}
{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Solicitação de Impressão
            <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
        </h1>
        <ol class="breadcrumb">
            <li><i class="fa fa-print"></i> Requisição de Impressão</li>
            <li class="active">Pesquisar Usuário</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
            <!-- Default box -->
            <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Pesquisar Usuário</h3>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="search-user">
                        <form class="navbar-form navbar-left" role="search" method="get">
                            <div class="form-group">
                            <input type="text" class="form-control" placeholder="Pesquisar Usuário" name="q">
                            </div>
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="box-body">
            	{% for user in object_list %}
            	<div class="media">
				  <div class="media-left">
				    <a href="{% url 'ctrl_p:user-details' user.pk %}">
				      <img src="{{ user.picture_thumb.url }}" class="user-image img-circle" alt="User Image" height="75">
				    </a>
				  </div>
				  <div class="media-body">
				    <a href="{% url 'ctrl_p:user-details' user.pk %}"><h4 class="media-heading">{{user.first_name}} {{user.last_name}}</h4></a>
				    <p>{{user.registration}}</p>
				  </div>
				</div>
				{% endfor %}
            </div>

            </div>
            <!-- /.box-body -->
            <!-- /.box-footer-->
            </div>
            <!-- /.box -->
        
        </section>
        <!-- /.content -->
{% endblock %}

templates/ctrl_p/admin/success.html
{% extends '../../core/base.html' %}

{% block content %}
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <h1>
      Solicitação de Impressão
      <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
    </h1>
    <ol class="breadcrumb">
      <li><i class="fa fa-print"></i> Requisição de Impressão</li>
      <li>Atualizar Arquivo</li>
      <li class="active">Sucesso</li>
    </ol>
  </section>

  <!-- Main content -->
  <section class="content">

    <!-- Default box -->
    <div class="box">
      <div class="box-header with-border">
        <h3 class="box-title">Sucesso</h3>

      </div>
      <div class="box-body">
        <div class="callout callout-success">
        <h4>Sucesso</h4>
        <p>O status do arquivo foi atualizado com sucesso! Logo o usuário solicitador receberá um e-mail informando o novo status. <a href="{% url 'ctrl_p:admin-printer' request.user.id %}">Clique aqui para voltar para a página inicial.</a></p>
      </div>
      </div>
      <!-- /.box-body -->

    </div>
    <!-- /.box -->

  </section>
  <!-- /.content -->
{% endblock %}

templates/ctrl_p/admin/waiting.html
{% extends '../../core/base.html' %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Solicitação de Impressão
            <small>Sistema de impressão do IFPB Campus Cajazeiras</small>
        </h1>
        <ol class="breadcrumb">
          <li><i class="fa fa-print"></i> Requisição de Impressão</li>
          <li class="active">Aguardando Retirada</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
            <!-- Default box -->
            <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Painel Administrativo - Arquivos Aguardando Retirada</h3>
            </div>
            <div class="box-body">
            <!-- Inicio da Aplicação -->
            <div class="search-user">
                <form class="navbar-form navbar-left" role="search" method="get" action="/results">
                    <div class="form-group">
                    <input type="text" class="form-control" placeholder="Pesquisar Usuário" name="q">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="col-md-12">
                {% if files_waiting|length > 0 %}
                <table class="table">
                <thead>
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome do Documento</th>
                    <th scope="col">Data da Solicitação</th>
                    <th scope="col">Solicitador</th>
                    <th scope="col">Status</th>
                    <th scope="col">Opções</th>
                  </tr>
                </thead>
                <tbody>
                    {% for file in files_waiting %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'ctrl_p:view-file' file.pk %}">{{ file.name }}</a></td>
                        <td>{{ file.uploaded|date:"d/m/Y" }} às {{ file.uploaded|time }}</td>
                        <td><a href="{% url 'ctrl_p:user-details' file.user.pk %}">{{ file.user }} {{ file.user.last_name }}</a></td>
                        <td><span class="label label-warning">Aguardando Retirada</span></td>
                        <td><a href="{% url 'ctrl_p:file-update' file.pk %}"><i class="fa fa-pencil-square-o" aria-hidden="true" title="Editar"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
              {% else %}
              <div class="not-found">
                <h3>Nenhum arquivo aguardando retirada</h3>
              </div>
              {% endif %}
            </div>
            </div>

            </div>
            </div>
            <!-- /.box -->
        
        </section>
        <!-- /.content -->
{% endblock %}